cal.math.get:
    url: '/calculate'
    controller: 'QL\CJarvis\MVC\Controllers\Calc\Get'
    view: 'calculate.twig'
    method: 'GET'

cal.math.post:
    url: '/calculate'
    controller: 'QL\CJarvis\MVC\Controllers\Calc\Post'
    view: 'calculate.twig'
    method: 'POST'

wea.api.get:
    url: '/weather'
    controller: 'QL\CJarvis\MVC\Controllers\Weather\Get'
    view: 'weather.twig'
    method: 'GET'

wea.api.post:
    url: '/weather'
    controller: 'QL\CJarvis\MVC\Controllers\Weather\Post'
    view: 'weather.twig'
    method: 'POST'
    